# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-29 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commet_type',
            new_name='comment_type',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='parent_commet',
            new_name='parent_comment',
        ),
    ]
